---
- name: "Synchronize local ~/.zsh/ into {{ inventory_hostname }}:~/.zsh/"
  synchronize:
    src: "{{ lookup('env','HOME') }}/.zsh/"
    dest: "{{ zsh_dir }}/"
    rsync_opts:
      - "--archive"
      - "--delete"
  delegate_to: localhost
  #when: ansible_connection != "local"